inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 100
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'slow_your_roles.gemspec'
AllCops:
  Exclude:
    - 'spec/**/*'
